package com.google.android.gms.internal;

import com.google.android.gms.ads.internal.f;
import java.util.List;
import java.util.concurrent.TimeUnit;

@eh
public final class aq {
    public static final am<Boolean> AE;
    public static final am<Boolean> AL;
    public static final am<String> AR;
    public static final am<Boolean> An;
    public static final am<Boolean> BR;
    public static final am<Boolean> BT;
    public static final am<Boolean> Bx;
    public static final am<String> CU;
    public static final am<Boolean> Cz;
    public static final am<String> DW;
    public static final am<String> E4;
    public static final am<String> EQ;
    public static final am<String> Ej;
    public static final am<Integer> Eq;
    public static final am<Boolean> Ev;
    public static final am<Boolean> FH;
    public static final am<String> FN;
    public static final am<String> Fd;
    public static final am<Boolean> GK;
    public static final am<Boolean> GT;
    public static final am<String> Gj;
    public static final am<String> Hl;
    public static final am<String> Hw;
    public static final am<String> I;
    public static final am<Boolean> IS;
    public static final am<String> J0;
    public static final am<Boolean> J8;
    public static final am<Long> Jl;
    public static final am<Integer> Jm;
    public static final am<Boolean> KD;
    public static final am<String> Lz;
    public static final am<String> MP;
    public static final am<Long> Mr;
    public static final am<Long> Mz;
    public static final am<Long> Nh;
    public static final am<Boolean> OW;
    public static final am<Long> Of;
    public static final am<Boolean> P8;
    public static final am<Long> PH;
    public static final am<String> PT;
    public static final am<Long> Pa;
    public static final am<Boolean> Q6;
    public static final am<Boolean> QO;
    public static final am<Integer> QX;
    public static final am<Boolean> Qq;
    public static final am<String> SI;
    public static final am<Integer> Sf;
    public static final am<Boolean> T6;
    public static final am<Long> TI;
    public static final am<Integer> U2;
    public static final am<Boolean> VH;
    public static final am<String> WB;
    public static final am<String> Ws;
    public static final am<String> XG;
    public static final am<Integer> XL;
    public static final am<Boolean> XX;
    public static final am<String> Xa;
    public static final am<Boolean> Yi;
    public static final am<Long> Z1;
    public static final am<String> Za;
    public static final am<String> Zo;
    public static final am<Boolean> a5;
    public static final am<Boolean> a8;
    public static final am<Integer> aM;
    public static final am<Boolean> aX;
    public static final am<String> aj;
    public static final am<Integer> aq;
    public static final am<Boolean> b1;
    public static final am<Integer> br;
    public static final am<Boolean> cT;
    public static final am<String> ca;
    public static final am<Integer> cb;
    public static final am<Boolean> cc;
    public static final am<Integer> ce;
    public static final am<Boolean> cn;
    public static final am<String> ct;
    public static final am<Boolean> dW;
    public static final am<Integer> dx;
    public static final am<String> e3;
    public static final am<Boolean> e9;
    public static final am<Long> eU;
    public static final am<Integer> ef;
    public static final am<String> ei;
    public static final am<String> er;
    public static final am<Boolean> et;
    public static final am<Boolean> fN;
    public static final am<Boolean> fY;
    public static final am<Boolean> g3;
    public static final am<String> gG;
    public static final am<String> gW;
    public static final am<Boolean> gn;
    public static final am<Boolean> hK;
    public static final am<String> hp;
    public static final am<Integer> hz;
    public static final am<Boolean> iW;
    public static final am<Long> j3;
    public static final am<String> j6;
    public static final am<Boolean> jJ;
    public static final am<String> jO;
    public static final am<Long> jw;
    public static final am<Boolean> k2;
    public static final am<String> kQ;
    public static final am<Long> kf;
    public static final am<String> ko;
    public static final am<String> lg;
    public static final am<Boolean> lp;
    public static final am<Boolean> mb;
    public static final am<Boolean> n5;
    public static final am<String> nw;
    public static final am<String> oY;
    public static final am<String> oa;
    public static final am<Long> oh;
    public static final am<String> oy;
    public static final am<Boolean> pN;
    public static final am<Boolean> pO;
    public static final am<String> pl;
    public static final am<String> q7;
    public static final am<Long> qP;
    public static final am<Boolean> qp;
    public static final am<Long> rN;
    public static final am<String> ro;
    public static final am<Boolean> sE;
    public static final am<Integer> sG;
    public static final am<Boolean> sM;
    public static final am<String> sT;
    public static final am<String> sg;
    public static final am<Boolean> sh;
    public static final am<Boolean> sy;
    public static final am<Boolean> tp;
    public static final am<String> u7;
    public static final am<Boolean> v5;
    public static final am<Boolean> vJ;
    public static final am<Boolean> vy;
    public static final am<Boolean> w9;
    public static final am<Boolean> wc;
    public static final am<String> we;
    public static final am<Boolean> x9;
    public static final am<String> xg;
    public static final am<String> yO;
    public static final am<Boolean> yS;
    public static final am<Boolean> ye;
    public static final am<Boolean> ys;
    public static final am<Boolean> zh;

    static {
        j6 = am.j6(0, "gads:sdk_core_experiment_id");
        DW = am.j6(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        FH = am.j6(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        Hw = am.j6(0, "gads:request_builder:singleton_webview_experiment_id");
        v5 = am.j6(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        Zo = am.j6(0, "gads:sdk_use_dynamic_module_experiment_id");
        VH = am.j6(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        gn = am.j6(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        u7 = am.j6(0, "gads:sdk_crash_report_class_prefix", "com.google.");
        tp = am.j6(0, "gads:block_autoclicks", Boolean.valueOf(false));
        EQ = am.j6(0, "gads:block_autoclicks_experiment_id");
        we = am.DW(0, "gads:prefetch:experiment_id");
        J0 = am.j6(0, "gads:spam_app_context:experiment_id");
        J8 = am.j6(0, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        Ws = am.j6(0, "gads:video_stream_cache:experiment_id");
        QX = am.j6(0, "gads:video_stream_cache:limit_count", 5);
        XL = am.j6(0, "gads:video_stream_cache:limit_space", 8388608);
        aM = am.j6(0, "gads:video_stream_exo_cache:buffer_size", 8388608);
        j3 = am.j6(0, "gads:video_stream_cache:limit_time_sec", 300);
        Mr = am.j6(0, "gads:video_stream_cache:notify_interval_millis", 1000);
        U2 = am.j6(0, "gads:video_stream_cache:connect_timeout_millis", 10000);
        a8 = am.j6(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        lg = am.j6(0, "gads:video:metric_frame_hash_times", "");
        rN = am.j6(0, "gads:video:metric_frame_hash_time_leniency", 500);
        er = am.DW(0, "gads:spam_ad_id_decorator:experiment_id");
        yS = am.j6(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        gW = am.DW(0, "gads:looper_for_gms_client:experiment_id");
        BT = am.j6(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        vy = am.j6(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        P8 = am.j6(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        ei = am.j6(0, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        nw = am.j6(0, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        SI = am.j6(0, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        KD = am.j6(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        ro = am.j6(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        cn = am.j6(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        sh = am.j6(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        cb = am.j6(0, "gads:content_length_weight", 1);
        dx = am.j6(0, "gads:content_age_weight", 1);
        sG = am.j6(0, "gads:min_content_len", 11);
        ef = am.j6(0, "gads:fingerprint_number", 10);
        Sf = am.j6(0, "gads:sleep_sec", 10);
        vJ = am.j6(0, "gad:app_index_enabled", Boolean.valueOf(true));
        g3 = am.j6(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        Mz = am.j6(0, "gads:app_index:timeout_ms", 1000);
        I = am.j6(0, "gads:app_index:experiment_id");
        ca = am.j6(0, "gads:kitkat_interstitial_workaround:experiment_id");
        x9 = am.j6(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        Qq = am.j6(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        sy = am.j6(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        aj = am.j6(0, "gads:interstitial_follow_url:experiment_id");
        lp = am.j6(0, "gads:analytics_enabled", Boolean.valueOf(true));
        OW = am.j6(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        br = am.j6(0, "gads:webview_cache_version", 0);
        XX = am.j6(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
        kQ = am.j6(1, "gads:webview_recycle:experiment_id");
        yO = am.DW(0, "gads:pan:experiment_id");
        XG = am.j6(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        jJ = am.j6(0, "gads:ad_manager_creator:enabled", Boolean.valueOf(true));
        wc = am.j6(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        et = am.j6(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        CU = am.j6(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        Xa = am.j6(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        Eq = am.j6(1, "gads:interstitial_ad_pool:max_pools", 3);
        hz = am.j6(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        aq = am.j6(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        FN = am.j6(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        jO = am.j6(1, "gads:spherical_video:vertex_shader", "");
        oY = am.j6(1, "gads:spherical_video:fragment_shader", "");
        ko = am.j6(1, "gads:spherical_video:experiment_id");
        Ev = am.j6(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        ye = am.j6(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
        WB = am.j6(1, "gads:include_local_global_rectangles:experiment_id");
        mb = am.j6(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        jw = am.j6(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        fY = am.j6(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        qp = am.j6(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        k2 = am.j6(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        zh = am.j6(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        AL = am.j6(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        w9 = am.j6(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        hK = am.j6(0, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(false));
        cT = am.j6(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        q7 = am.j6(0, "gads:gmsg:video_meta:experiment_id");
        Z1 = am.j6(0, "gads:network:cache_prediction_duration_s", 300);
        n5 = am.j6(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        Q6 = am.j6(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        kf = am.j6(0, "gads:ad_loader:timeout_ms", 60000);
        Jl = am.j6(0, "gads:rendering:timeout_ms", 60000);
        iW = am.j6(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        eU = am.j6(1, "gads:gestures:task_timeout", 2000);
        e3 = am.j6(1, "gads:gestures:encrypt_size_limit:experiment_id");
        sE = am.j6(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(true));
        sg = am.j6(1, "gads:gestures:cpu:experiment_id");
        pO = am.j6(1, "gads:gestures:cpu_query:enabled", Boolean.valueOf(false));
        fN = am.j6(1, "gads:gestures:cpu_click:enabled", Boolean.valueOf(false));
        Gj = am.j6(1, "gads:gestures:jbk:experiment_id");
        Cz = am.j6(1, "gads:gestures:jbk_query:enabled", Boolean.valueOf(false));
        pN = am.j6(1, "gads:gestures:jbk_click:enabled", Boolean.valueOf(false));
        oy = am.j6(1, "gads:gestures:stk:experiment_id");
        aX = am.j6(1, "gads:gestures:stk:enabled", Boolean.valueOf(false));
        e9 = am.j6(0, "gass:enabled", Boolean.valueOf(false));
        QO = am.j6(0, "gass:enable_int_signal", Boolean.valueOf(true));
        sM = am.j6(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        a5 = am.j6(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        ys = am.j6(0, "gads:support_screen_shot", Boolean.valueOf(true));
        IS = am.j6(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        gG = am.j6(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        Nh = am.j6(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        BR = am.j6(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        AE = am.j6(1, "gads:singleton_webview_native", Boolean.valueOf(false));
        Za = am.j6(1, "gads:singleton_webview_native:experiment_id");
        An = am.j6(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
        Pa = am.j6(0, "gads:method_tracing:duration_ms", 30000);
        ce = am.j6(0, "gads:method_tracing:count", 5);
        Jm = am.j6(0, "gads:method_tracing:filesize", 134217728);
        Bx = am.j6(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        oa = am.DW(1, "gads:auto_location_for_coarse_permission:experiment_id");
        qP = am.j6(1, "gads:auto_location_timeout", 2000);
        MP = am.DW(1, "gads:auto_location_timeout:experiment_id");
        Of = am.j6(1, "gads:auto_location_interval", -1);
        PT = am.DW(1, "gads:auto_location_interval:experiment_id");
        b1 = am.j6(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        AR = am.j6(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        TI = am.j6(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        ct = am.j6(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
        Fd = am.j6(0, "gads:afs:csa:experiment_id");
        Lz = am.j6(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        sT = am.j6(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        E4 = am.j6(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        xg = am.j6(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        hp = am.j6(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        PH = am.j6(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
        GK = am.j6(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        dW = am.j6(0, "gads:safe_browsing:reporting:malicious:enabled", Boolean.valueOf(false));
        Yi = am.j6(0, "gads:safe_browsing:reporting:full:enabled", Boolean.valueOf(false));
        GT = am.j6(0, "gads:safe_browsing:screenshot:enabled", Boolean.valueOf(false));
        Hl = am.j6(0, "gads:safe_browsing:reporting:url", "https://sb-ssl.google.com/safebrowsing/clientreport/malware");
        pl = am.j6(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        oh = am.j6(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        Ej = am.j6(0, "gads:safe_browsing:experiment_id");
        T6 = am.j6(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
        cc = am.j6(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    }

    public static List<String> j6() {
        return f.gn().j6();
    }
}
