package com.google.android.gms.common.api.p155a;

import com.google.android.gms.common.api.C3304d;
import com.google.android.gms.common.api.C3304d.C3300a;
import com.google.android.gms.common.api.C3386f;
import com.google.android.gms.common.api.C3442g;
import com.google.android.gms.common.api.Status;

/* renamed from: com.google.android.gms.common.api.a.p */
public class C3434p<R extends C3386f> extends C3304d<R> {
    private final Status f11946a;

    public Integer m14196a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void m14197a(C3300a c3300a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void m14198a(C3442g<? super R> c3442g) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status m14199b() {
        return this.f11946a;
    }
}
