public interface bca {
    public static final ayq BT;
    public static final ayq DW;
    public static final ayq EQ;
    public static final ayq FH;
    public static final ayq Hw;
    public static final ayq J0;
    public static final ayq J8;
    public static final ayq Mr;
    public static final ayq P8;
    public static final ayq QX;
    public static final ayq U2;
    public static final ayq VH;
    public static final ayq Ws;
    public static final ayq XL;
    public static final ayq Zo;
    public static final ayq a8;
    public static final ayq aM;
    public static final ayq ei;
    public static final ayq er;
    public static final ayq gW;
    public static final ayq gn;
    public static final ayq j3;
    public static final ayq j6;
    public static final ayq lg;
    public static final ayq nw;
    public static final ayq rN;
    public static final ayq tp;
    public static final ayq u7;
    public static final ayq v5;
    public static final ayq vy;
    public static final ayq we;
    public static final ayq yS;

    static {
        j6 = new ayq("2.16.840.1.101.3.4");
        DW = j6.DW("2.1");
        FH = j6.DW("2.2");
        Hw = j6.DW("2.3");
        v5 = j6.DW("2.4");
        Zo = j6.DW("1");
        VH = Zo.DW("1");
        gn = Zo.DW("2");
        u7 = Zo.DW("3");
        tp = Zo.DW("4");
        EQ = Zo.DW("5");
        we = Zo.DW("6");
        J0 = Zo.DW("7");
        J8 = Zo.DW("21");
        Ws = Zo.DW("22");
        QX = Zo.DW("23");
        XL = Zo.DW("24");
        aM = Zo.DW("25");
        j3 = Zo.DW("26");
        Mr = Zo.DW("27");
        U2 = Zo.DW("41");
        a8 = Zo.DW("42");
        lg = Zo.DW("43");
        rN = Zo.DW("44");
        er = Zo.DW("45");
        yS = Zo.DW("46");
        gW = Zo.DW("47");
        BT = j6.DW("3");
        vy = BT.DW("1");
        P8 = BT.DW("2");
        ei = BT.DW("3");
        nw = BT.DW("4");
    }
}
