public interface bce {
    public static final ayq AE;
    public static final ayq AL;
    public static final ayq AR;
    public static final ayq An;
    public static final ayq BR;
    public static final ayq BT;
    public static final ayq Bx;
    public static final ayq CU;
    public static final ayq Cz;
    public static final ayq EQ;
    public static final ayq Eq;
    public static final ayq Ev;
    public static final ayq FN;
    public static final ayq Fd;
    public static final ayq Gj;
    public static final ayq Hw;
    public static final ayq I;
    public static final ayq IS;
    public static final ayq Jl;
    public static final ayq Jm;
    public static final ayq KD;
    public static final ayq Lz;
    public static final ayq MP;
    public static final ayq Mz;
    public static final ayq Nh;
    public static final ayq OW;
    public static final ayq Of;
    public static final ayq P8;
    public static final ayq PT;
    public static final ayq Pa;
    public static final ayq Q6;
    public static final ayq QO;
    public static final ayq Qq;
    public static final ayq SI;
    public static final ayq Sf;
    public static final ayq TI;
    public static final ayq U2;
    public static final ayq WB;
    public static final ayq XG;
    public static final ayq XL;
    public static final ayq XX;
    public static final ayq Xa;
    public static final ayq Z1;
    public static final ayq Za;
    public static final ayq a5;
    public static final ayq a8;
    public static final ayq aX;
    public static final ayq a_;
    public static final ayq aj;
    public static final ayq aq;
    public static final ayq b1;
    public static final ayq b_;
    public static final ayq br;
    public static final ayq cT;
    public static final ayq c_;
    public static final ayq ca;
    public static final ayq cb;
    public static final ayq ce;
    public static final ayq cn;
    public static final ayq ct;
    public static final ayq d_;
    public static final ayq dx;
    public static final ayq e3;
    public static final ayq e9;
    public static final ayq eU;
    public static final ayq e_;
    public static final ayq ef;
    public static final ayq ei;
    public static final ayq er;
    public static final ayq et;
    public static final ayq fN;
    public static final ayq fY;
    public static final ayq f_;
    public static final ayq g3;
    public static final ayq gG;
    public static final ayq gW;
    public static final ayq g_;
    public static final ayq gn;
    public static final ayq hK;
    public static final ayq h_;
    public static final ayq hz;
    public static final ayq iW;
    public static final ayq i_;
    public static final ayq jJ;
    public static final ayq jO;
    public static final ayq j_;
    public static final ayq jw;
    public static final ayq k2;
    public static final ayq kQ;
    public static final ayq k_;
    public static final ayq kf;
    public static final ayq ko;
    public static final ayq l_;
    public static final ayq lg;
    public static final ayq lp;
    public static final ayq m_;
    public static final ayq mb;
    public static final ayq n5;
    public static final ayq n_;
    public static final ayq nw;
    public static final ayq oY;
    public static final ayq oa;
    public static final ayq oy;
    public static final ayq pN;
    public static final ayq pO;
    public static final ayq q7;
    public static final ayq qP;
    public static final ayq qp;
    public static final ayq rN;
    public static final ayq ro;
    public static final ayq sE;
    public static final ayq sG;
    public static final ayq sM;
    public static final ayq sT;
    public static final ayq sg;
    public static final ayq sh;
    public static final ayq sy;
    public static final ayq tp;
    public static final ayq v5;
    public static final ayq vJ;
    public static final ayq vy;
    public static final ayq w9;
    public static final ayq wc;
    public static final ayq x9;
    public static final ayq yO;
    public static final ayq yS;
    public static final ayq ye;
    public static final ayq ys;
    public static final ayq zh;

    static {
        a_ = new ayq("1.2.840.113549.1.1");
        b_ = a_.DW("1");
        c_ = a_.DW("2");
        Hw = a_.DW("3");
        v5 = a_.DW("4");
        d_ = a_.DW("5");
        e_ = a_.DW("6");
        gn = a_.DW("7");
        f_ = a_.DW("8");
        tp = a_.DW("9");
        EQ = a_.DW("10");
        g_ = a_.DW("11");
        h_ = a_.DW("12");
        i_ = a_.DW("13");
        j_ = a_.DW("14");
        k_ = new ayq("1.2.840.113549.1.3");
        XL = k_.DW("1");
        l_ = new ayq("1.2.840.113549.1.5");
        m_ = l_.DW("1");
        n_ = l_.DW("4");
        U2 = l_.DW("3");
        a8 = l_.DW("6");
        lg = l_.DW("10");
        rN = l_.DW("11");
        er = l_.DW("13");
        yS = l_.DW("12");
        gW = new ayq("1.2.840.113549.3");
        BT = gW.DW("7");
        vy = gW.DW("2");
        P8 = new ayq("1.2.840.113549.2");
        ei = P8.DW("2");
        nw = P8.DW("4");
        SI = P8.DW("5");
        KD = P8.DW("7");
        ro = P8.DW("8");
        cn = P8.DW("9");
        sh = P8.DW("10");
        cb = P8.DW("11");
        dx = new ayq("1.2.840.113549.1.7.1");
        sG = new ayq("1.2.840.113549.1.7.2");
        ef = new ayq("1.2.840.113549.1.7.3");
        Sf = new ayq("1.2.840.113549.1.7.4");
        vJ = new ayq("1.2.840.113549.1.7.5");
        g3 = new ayq("1.2.840.113549.1.7.6");
        Mz = new ayq("1.2.840.113549.1.9");
        I = Mz.DW("1");
        ca = Mz.DW("2");
        x9 = Mz.DW("3");
        Qq = Mz.DW("4");
        sy = Mz.DW("5");
        aj = Mz.DW("6");
        lp = Mz.DW("7");
        OW = Mz.DW("8");
        br = Mz.DW("9");
        XX = Mz.DW("13");
        kQ = Mz.DW("14");
        yO = Mz.DW("15");
        XG = Mz.DW("20");
        jJ = Mz.DW("21");
        wc = Mz.DW("22.1");
        et = Mz.DW("22");
        CU = et.DW("1");
        Xa = et.DW("2");
        Eq = Mz.DW("23");
        hz = Eq.DW("1");
        aq = Mz.DW("16.3.9");
        FN = Mz.DW("15.1");
        jO = Mz.DW("15.2");
        oY = Mz.DW("15.3");
        ko = new ayq("1.2.840.113549.1.9.16.1");
        Ev = ko.DW("2");
        ye = ko.DW("4");
        WB = ko.DW("9");
        mb = ko.DW("23");
        jw = ko.DW("31");
        fY = new ayq("1.2.840.113549.1.9.16.6");
        qp = fY.DW("1");
        k2 = fY.DW("2");
        zh = fY.DW("3");
        AL = fY.DW("4");
        w9 = fY.DW("5");
        hK = fY.DW("6");
        cT = new ayq("1.2.840.113549.1.9.16.2");
        q7 = cT.DW("1");
        Z1 = cT.DW("4");
        n5 = cT.DW("5");
        Q6 = cT.DW("10");
        kf = cT.DW("11");
        Jl = cT.DW("12");
        iW = cT.DW("47");
        eU = cT.DW("7");
        e3 = cT.DW("14");
        sE = cT.DW("15");
        sg = cT.DW("16");
        pO = cT.DW("17");
        fN = cT.DW("18");
        Gj = cT.DW("19");
        Cz = cT.DW("20");
        pN = cT.DW("21");
        oy = cT.DW("22");
        aX = cT.DW("23");
        e9 = cT.DW("24");
        QO = cT.DW("25");
        sM = cT.DW("26");
        a5 = cT.DW("27");
        ys = sE;
        IS = sg;
        gG = pO;
        Nh = Gj;
        BR = new ayq("1.2.840.113549.1.9.16.5.1");
        AE = new ayq("1.2.840.113549.1.9.16.5.2");
        Za = new ayq("1.2.840.113549.1.12");
        An = Za.DW("10.1");
        Pa = An.DW("1");
        ce = An.DW("2");
        Jm = An.DW("3");
        Bx = An.DW("4");
        oa = An.DW("5");
        qP = An.DW("6");
        MP = Za.DW("1");
        Of = MP.DW("1");
        PT = MP.DW("2");
        b1 = MP.DW("3");
        AR = MP.DW("4");
        TI = MP.DW("5");
        ct = MP.DW("6");
        Fd = MP.DW("6");
        Lz = new ayq("1.2.840.113549.1.9.16.3.6");
        sT = new ayq("1.2.840.113549.1.9.16.3.7");
    }
}
