public interface bdj {
    public static final ayq BT;
    public static final ayq CU;
    public static final ayq DW;
    public static final ayq EQ;
    public static final ayq FH;
    public static final ayq Hw;
    public static final ayq I;
    public static final ayq J0;
    public static final ayq J8;
    public static final ayq KD;
    public static final ayq Mr;
    public static final ayq Mz;
    public static final ayq OW;
    public static final ayq P8;
    public static final ayq QX;
    public static final ayq Qq;
    public static final ayq SI;
    public static final ayq Sf;
    public static final ayq U2;
    public static final ayq VH;
    public static final ayq Ws;
    public static final ayq XG;
    public static final ayq XL;
    public static final ayq XX;
    public static final ayq Xa;
    public static final ayq Zo;
    public static final ayq a8;
    public static final ayq aM;
    public static final ayq aj;
    public static final ayq br;
    public static final ayq ca;
    public static final ayq cb;
    public static final ayq cn;
    public static final ayq dx;
    public static final ayq ef;
    public static final ayq ei;
    public static final ayq er;
    public static final ayq et;
    public static final ayq g3;
    public static final ayq gW;
    public static final ayq gn;
    public static final ayq j3;
    public static final ayq j6;
    public static final ayq jJ;
    public static final ayq kQ;
    public static final ayq lg;
    public static final ayq lp;
    public static final ayq nw;
    public static final ayq rN;
    public static final ayq ro;
    public static final ayq sG;
    public static final ayq sh;
    public static final ayq sy;
    public static final ayq tp;
    public static final ayq u7;
    public static final ayq v5;
    public static final ayq vJ;
    public static final ayq vy;
    public static final ayq wc;
    public static final ayq we;
    public static final ayq x9;
    public static final ayq yO;
    public static final ayq yS;

    static {
        j6 = new ayq("1.2.840.10045");
        DW = j6.DW("1");
        FH = DW.DW("1");
        Hw = DW.DW("2");
        v5 = DW.DW("2.3.1");
        Zo = DW.DW("2.3.2");
        VH = DW.DW("2.3.3");
        gn = j6.DW("4");
        u7 = new ayq(gn + ".1");
        tp = j6.DW("2");
        EQ = tp.DW("1");
        we = gn.DW("3");
        J0 = we.DW("1");
        J8 = we.DW("2");
        Ws = we.DW("3");
        QX = we.DW("4");
        XL = j6.DW("3");
        aM = XL.DW("0");
        j3 = aM.DW("1");
        Mr = aM.DW("2");
        U2 = aM.DW("3");
        a8 = aM.DW("4");
        lg = aM.DW("5");
        rN = aM.DW("6");
        er = aM.DW("7");
        yS = aM.DW("8");
        gW = aM.DW("9");
        BT = aM.DW("10");
        vy = aM.DW("11");
        P8 = aM.DW("12");
        ei = aM.DW("13");
        nw = aM.DW("14");
        SI = aM.DW("15");
        KD = aM.DW("16");
        ro = aM.DW("17");
        cn = aM.DW("18");
        sh = aM.DW("19");
        cb = aM.DW("20");
        dx = XL.DW("1");
        sG = dx.DW("1");
        ef = dx.DW("2");
        Sf = dx.DW("3");
        vJ = dx.DW("4");
        g3 = dx.DW("5");
        Mz = dx.DW("6");
        I = dx.DW("7");
        ca = new ayq("1.2.840.10040.4.1");
        x9 = new ayq("1.2.840.10040.4.3");
        Qq = new ayq("1.3.133.16.840.63.0");
        sy = Qq.DW("2");
        aj = Qq.DW("3");
        lp = Qq.DW("16");
        OW = new ayq("1.2.840.10046");
        br = OW.DW("2.1");
        XX = OW.DW("3");
        kQ = XX.DW("1");
        yO = XX.DW("2");
        XG = XX.DW("3");
        jJ = XX.DW("4");
        wc = XX.DW("5");
        et = XX.DW("6");
        CU = XX.DW("7");
        Xa = XX.DW("8");
    }
}
