public interface bch {
    public static final ayq BT;
    public static final ayq DW;
    public static final ayq EQ;
    public static final ayq FH;
    public static final ayq Hw;
    public static final ayq J0;
    public static final ayq J8;
    public static final ayq Mr;
    public static final ayq QX;
    public static final ayq U2;
    public static final ayq VH;
    public static final ayq Ws;
    public static final ayq XL;
    public static final ayq Zo;
    public static final ayq a8;
    public static final ayq aM;
    public static final ayq er;
    public static final ayq gW;
    public static final ayq gn;
    public static final ayq j3;
    public static final ayq j6;
    public static final ayq lg;
    public static final ayq rN;
    public static final ayq tp;
    public static final ayq u7;
    public static final ayq v5;
    public static final ayq we;
    public static final ayq yS;

    static {
        j6 = new ayq("1.3.36.3");
        DW = j6.DW("2.1");
        FH = j6.DW("2.2");
        Hw = j6.DW("2.3");
        v5 = j6.DW("3.1");
        Zo = v5.DW("2");
        VH = v5.DW("3");
        gn = v5.DW("4");
        u7 = j6.DW("3.2");
        tp = u7.DW("1");
        EQ = u7.DW("2");
        we = j6.DW("3.2.8");
        J0 = we.DW("1");
        J8 = J0.DW("1");
        Ws = J8.DW("1");
        QX = J8.DW("2");
        XL = J8.DW("3");
        aM = J8.DW("4");
        j3 = J8.DW("5");
        Mr = J8.DW("6");
        U2 = J8.DW("7");
        a8 = J8.DW("8");
        lg = J8.DW("9");
        rN = J8.DW("10");
        er = J8.DW("11");
        yS = J8.DW("12");
        gW = J8.DW("13");
        BT = J8.DW("14");
    }
}
